name: Build w/ Hugo & deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Update submodules
        uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --remote --merge

      - name: Build
        run: docker run --rm --volume $PWD:/src -w "/src" bwklein/hugo-asciidoctor hugo --minify -v

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          # or github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
